# Generated by Django 4.2.14 on 2024-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_art',
            field=models.CharField(choices=[('AR', 'article'), ('NE', 'news')], default='NE', max_length=2),
        ),
    ]
